apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-pods
  template:
    metadata:
      labels:
        app: demo-pods
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
      - name: pinger
        image: centos:7
        command: ["ping", "8.8.8.8"]
