apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
  labels:
    env: preprod
    appli: monapp
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-pods
  template:
    metadata:
      labels:
        app: demo-pods
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
      - name: pinger
        image: centos:7
        command: ["ping", "4.4.4.4"]
