apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
spec:
  containers:
  - name: pod-cm
    image: alpine:latest
    command: 
      - "/bin/sh"
      - "-ec"
      - "while :; do echo '.'; sleep 5 ; done"
    envFrom:
      - configMapRef:
          name: game-config-env-file
        prefix: cm-
    env:
      - name: TEST_ENV_VAR
        valueFrom:
          configMapKeyRef:
            name: game-config-env-file
            key: enemies
