apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-mount
spec:
  containers:
    - name: test-container
      image: alpine:latest
      command:
        - "/bin/sh"
        - "-ec"
        - "while :; do echo '.'; sleep 5 ; done"
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      secret:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        secretName: dbuser
  restartPolicy: Never
