apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: pod-cm
    image: alpine:latest
    command: 
      - "/bin/sh"
      - "-ec"
      - "while :; do echo '.'; sleep 5 ; done"
    envFrom:
      - secretRef:
          name: db-user-pass
    env:
      - name: TEST_ENV_VAR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: password
