apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pods
  progressDeadlineSeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-pods
    spec:
      containers:
      - name: pinger
        image: centos:latest
        command: ["ping", "8.8.8.8"]
