apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - defaultRequest:
      memory: 256Mi
    max:
      memory: 256Mi
    maxLimitRequestRatio:
      memory: 1
    type: Container
