apiVersion: v1
kind: Pod
metadata:
  name: priv-escalation
  labels:
    name: priv-escalation
spec:
  containers:
  - name: priv-escalation
    image: dockerpac/priv-escalation:latest
    command: [ "/bin/sh", "-c", "sleep 240" ]
