apiVersion: v1
kind: Pod
metadata:
  name: priv-escalation-deny
  labels:
    name: priv-escalation-deny
spec:
  containers:
  - name: priv-escalation-deny
    image: centos:7
    command: [ "/bin/sh", "-c", "sleep 240" ]
    imagePullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      readOnlyRootFilesystem: false
