---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: 1Gi
    limits.cpu: "250m"
    limits.memory: 1Gi
  scopeSelector:
      matchExpressions:
      - operator : NotIn
        scopeName: PriorityClass
        values: ["high-priority"]
