apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: shared-data
        mountPath: /nginx-data
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
      - name: shared-data
        mountPath: /alpine-data
  volumes:
  - name: shared-data
    emptyDir: {}
