apiVersion: v1
kind: Service
metadata:
  name: destination-entrypoint-nodeport
  namespace: default
spec:
  selector:
    app: dest
  ports:
  - port: 8080
    targetPort: 8000
    nodePort: 33000
  type: NodePort
