apiVersion: v1
kind: Pod
metadata:
  name: pod-using-hostpath
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
      - name: shared-data
        mountPath: /alpine-data
  volumes:
  - name: shared-data
    hostPath:
      path: /tmp/podhostpath
    
