apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: disk
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/podhostpath/pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  labels:
    type: disk
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/podhostpath/pv2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
  labels:
    type: disk
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/podhostpath/pv3
